name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        working-directory: BasicSample
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: BasicSample/app/build/outputs/apk/debug/app-debug.apk
